### PR TITLE
Use `hasOwnProperty` instead of `length` for checking if property exist

### LINKED ISSUE #569: [RC] Errors in the Checkout page when paying with a disabled card (623)
### Describe the Bug

There are errors in the browser console on the Checkout page when paying with a disabled card.

This doesn't affect the payment flow as the customer still can't pay with a disabled card, as expected. But we shouldn't have errors in the console.

### To Reproduce

1. Make sure Card Processing is enabled
2. Add "Visa" to the "Disable specific credit cards" option
3. Go to the store and add a product to your cart
4. Select "Credit cards" as the payment method
5. Pay with a Visa card
6. Notice there're errors in the console. [Here's a video](https://d.pr/v/xX4p87) with the behavior

image

### Expected Behavior

There shouldn't be errors in the console.

### Actual Behavior

There're errors in the console.

### Environment

WordPress Version: 5.9.2
WooCommerce Version: 6.3.1
Plugin Version: 1.7.1-test2
Browser and Version: Chrome 99.0.4844.84
Any other plugins installed: None

### PR DESCRIPTION
**Pull request by Dinamiko**
Fixes #569.

### CODE REVIEW

File: modules/ppcp-button/resources/js/modules/Renderer/CreditCardRenderer.js [hunk 1]
```diff
@@ -218,7 +218,8 @@ class CreditCardRenderer {
             }).catch(err => {
                 this.spinner.unblock();
                 this.errorHandler.clear();
-                if (err.details.length > 0) {
+
+                if (err.hasOwnProperty('details')) {
```
Comment (AlexP11223) [inline modules/ppcp-button/resources/js/modules/Renderer/CreditCardRenderer.js]: hm, I think `hasOwnProperty` is not intended for such purposes.

Maybe just `if (err.details)`?

Also you can check `length` like this: `err.details?.length > 0`

**Review by AlexP11223 — CHANGES_REQUESTED** [review]

File: modules/ppcp-button/resources/js/modules/Renderer/CreditCardRenderer.js (hunk 1 above)
Comment (Dinamiko) [reply modules/ppcp-button/resources/js/modules/Renderer/CreditCardRenderer.js]: yup, much better with `err.details`, thanks.

**Review by AlexP11223 — APPROVED** [review]
