### PR TITLE
Fix the script loading check.

### LINKED ISSUE #750: [1.9.1] PayPal scripts loading on on pages without active smart buttons or Pay Later messaging (819)
### Describe the Bug

With version 1.9.1, PayPal scripts are loaded on all pages even if all smart buttons and Pay Later messaging are disabled.

### To Reproduce

1. install version 1.9.1
2. open browser network activity
3. load any page without an active PayPal button or Pay Later messaging
4. observe PayPal scripts loading anyway

### Expected Behavior

The PayPal scripts only load when smart buttons or the Pay Later messaging are enabled on a page.

### Actual Behavior

The PayPal scripts load when smart buttons or the Pay Later messaging are not enabled on a page.

### Environment

 - WordPress Version 6.0.1
 - WooCommerce Version 67.0
 - Plugin Version 1.9.1

### Possible cause

Behavior introduced with this commit: Fix messaging display when the buttons are disabled #692 

### Potential workaround
Downgrade to a previous version like 1.9.0 or 1.8.1 (available in [the Releases section](https://github.com/woocommerce/woocommerce-paypal-payments/releases)) or try it with [this package](https://drive.google.com/uc?export=download&id=1TP2LWrlJT2jZvPW7FH0ASrbpPHUdsTdg) which rolls back #692.

### PR DESCRIPTION
**Pull request by Narek13**
**Issue**: #750

---

### Description

With version 1.9.1, PayPal scripts are loaded on all pages even if all smart buttons and Pay Later messaging are disabled.
The PR will fix this problem by fixing the script loading check logic.

### Steps to Test

1. Install version 1.9.1.
2. Open browser network activity.
3. Load any page without an active PayPal button or Pay Later messaging.
4. Observe PayPal scripts loading anyway.

---

Closes #750 .

### CODE REVIEW

File: modules/ppcp-button/src/Assets/SmartButton.php [hunk 1]
```diff
@@ -1092,9 +1092,9 @@ private function load_button_component() : bool {
 		}
 		if (
 			$this->context() === 'product'
-			&& $this->settings->has( 'button_product_enabled' )
+			&& ( $this->settings->has( 'button_product_enabled' )
 			&& $this->settings->get( 'button_product_enabled' )
-			|| $this->settings->has( 'message_product_enabled' )
+			|| $this->settings->has( 'message_product_enabled' ) )
```
Comment (AlexP11223) [inline modules/ppcp-button/src/Assets/SmartButton.php]: I think it's missing `get`?

```
		if (
			$this->context() === 'product'
			&& (
				( $this->settings->has( 'button_product_enabled' ) && $this->settings->get( 'button_product_enabled' ) ) ||
				( $this->settings->has( 'message_product_enabled' ) && $this->settings->get( 'message_product_enabled' ) )
			)
		) {
```

Comment (Narek13) [reply modules/ppcp-button/src/Assets/SmartButton.php]: fixed a1454dbfd7e60928b6e1926c94c7f269b621f383

**Review by AlexP11223 — APPROVED** [review]
