### PR TITLE
Check the cart total amount inside mini cart buttons renderer hook.

### LINKED ISSUE #573: PayPal buttons not displayed in minicart. (626)
### Describe the Bug

PayPal buttons are not added in minicart. adding product to cart which is a first product in cart then the buttons will not be show, until you add another product into cart

### To Reproduce

1. Go to Shop.
2. Add product to cart.
3. Check minicart.
4. Reload page and check minicart.

### Expected Behavior

The buttons are shown in mini cart if the total price amount is not 0

### Actual Behavior

The buttons are not shown

### PR DESCRIPTION
**Pull request by Narek13**
**Issue**: #573

---

### Description

PayPal buttons are not added in minicart. adding product to cart which is a first product in cart then the buttons will not be show, until you add another product into cart.

The PR will fix the problem by making a check about cart total amount inside the button renderer hook.

### Steps to Test

1. Go to Shop.
2. Add product to cart.
3. Check minicart.
4. Reload page and check minicart.

---

Closes #573 .

### CODE REVIEW

File: modules/ppcp-button/src/Assets/SmartButton.php [hunk 1]
```diff
@@ -354,6 +354,27 @@ private function render_button_wrapper_registrar(): bool {
...
+		$not_enabled_on_minicart = $this->settings->has( 'button_mini_cart_enabled' ) &&
+			! $this->settings->get( 'button_mini_cart_enabled' );
+		if (
+		! $not_enabled_on_minicart
+		) {
+			add_action(
+				$this->mini_cart_button_renderer_hook(),
+				static function () {
+                    // phpcs:ignore WordPress.PHP.StrictComparisons.LooseComparison
+					if ( WC()->cart->get_cart_contents_total() == 0 ) {
```
Comment (AlexP11223) [inline modules/ppcp-button/src/Assets/SmartButton.php]: Why not call `is_cart_price_total_zero`?

**Review by AlexP11223 — CHANGES_REQUESTED** [review]

File: modules/ppcp-button/src/Assets/SmartButton.php (hunk 1 above)
Comment (Narek13) [reply modules/ppcp-button/src/Assets/SmartButton.php]: @AlexP11223 
I have tried to have a variable `$is_cart_price_total_zero = $this-> is_cart_price_total_zero()` and then `static function () use ($is_cart_price_total_zero )` but it returned wrong value, I guess because it was called outside of the hook. 

In other hands you can't call `$this` inside the `static` handler, right? or is there a better way?
Thanks

Comment (AlexP11223) [reply modules/ppcp-button/src/Assets/SmartButton.php]: You can if you either remove `static` here or make `is_cart_price_total_zero` `static`.

**Review by AlexP11223 — APPROVED** [review]

File: modules/ppcp-button/src/Assets/SmartButton.php (hunk 1 above)
Comment (Narek13) [reply modules/ppcp-button/src/Assets/SmartButton.php]: done 515a06542ed8aa652ac6d0b38b5e68de901f9c73
Thanks.

**Review by Dinamiko — APPROVED** [review]
