### PR TITLE
Tracking integration compatibility with Germanized plugin

### LINKED ISSUE #883: Tracking integration compatibility with Germanized plugin (905)
### Describe

It was proposed to have better integration of tracking functionality with [Germanized](https://wordpress.org/plugins/woocommerce-germanized/) plugin.

### To Reproduce

1. After saving the order shipment information the shipment info should be sent to PayPal as tracking info.

### Expected Behavior

After saving the order shipment information the shipment info should be sent to PayPal as tracking info.

### PR DESCRIPTION
**Pull request by Narek13**
**Issue**: #883

---

### Description

It was proposed to have better integration of tracking functionality with [Germanized](https://wordpress.org/plugins/woocommerce-germanized/) plugin.

The PR will add functionality, so that when saving the order shipment information the shipment info will be sent to PayPal as tracking info.

### Steps to Test

1. After saving the order shipment information the shipment info should be sent to PayPal as tracking info.

---

Closes #883 .

### CODE REVIEW

File: modules/ppcp-compat/resources/js/gzd-compat.js [hunk 1]
```diff
@@ -0,0 +1,39 @@
...
+        const loadLocation = location.href + " " + orderTrackingContainerSelector + ">*";
+
+        const disableTrackingFields = function () {
+            var childNodes = document.getElementById(orderTrackingContainerId).getElementsByTagName('*');
+            for (var node of childNodes) {
+                node.disabled = true;
+            }
+        }
+
+        const enableTrackingFields = function () {
```
Comment (AlexP11223) [inline modules/ppcp-compat/resources/js/gzd-compat.js]: Maybe create one function like `setEnabled...(bool)` to avoid duplication?

File: modules/ppcp-compat/services.php [hunk 2]
```diff
@@ -50,4 +52,62 @@
...
+		return function_exists( 'wc_gzd_get_shipments_by_order' ); // 3.0+
+	},
+
+	'compat.gzd.tracking_statuses_map'              => function ( ContainerInterface $container ): array {
+		$gzd_statuses = wc_gzd_get_shipment_statuses();
+		$status_map = array();
+
+		foreach ( $gzd_statuses as $gzd_status ) {
+			$gzd_status = strtolower( $gzd_status );
+			switch ( $gzd_status ) {
```
Comment (AlexP11223) [inline modules/ppcp-compat/services.php]: Why not just return array immediately?

```
return array(
    'draft' => 'ON_HOLD',
    ...
```

File: modules/ppcp-compat/webpack.config.js [hunk 3]
```diff
@@ -0,0 +1,35 @@
...
+    },
+    output: {
+        path: path.resolve(__dirname, 'assets/'),
+        filename: 'js/[name].js',
+    },
+    module: {
+        rules: [{
+            test: /\.js?$/,
+            exclude: /node_modules/,
+            loader: 'babel-loader',
```
Comment (AlexP11223) [inline modules/ppcp-compat/webpack.config.js:19]: You should also copy `.babelrc`

File: modules/ppcp-compat/resources/js/gzd-compat.js (hunk 1 above)
Comment (Narek13) [reply modules/ppcp-compat/resources/js/gzd-compat.js]: done 0f6dcc8aa8ee4b44727f77156be79b139f8766f9

File: modules/ppcp-compat/services.php (hunk 2 above)
Comment (Narek13) [reply modules/ppcp-compat/services.php]: done 7e19846c193df4637b7e5546c78b4fcc0d14347c

File: modules/ppcp-compat/webpack.config.js (hunk 3 above)
Comment (Narek13) [reply modules/ppcp-compat/webpack.config.js:19]: added 8f89226cb320c9b856500a7dcae39ce3580d5e6a

**Review by AlexP11223 — APPROVED** [review]

**Review by Dinamiko — APPROVED** [review]
