### PR TITLE
Do not increment step directly

### LINKED ISSUE #3707: Bug: PayPal Payments onboarding flow stuck (5712)
# Bug Report: Onboarding step value increases indefinitely and blocks activation

### Describe the Bug

When attempting to activate PayPal Payments in WooCommerce, the plugin increments the stored option `woocommerce-ppcp-data-onboarding[step]` on **every attempt**, regardless of whether the connection succeeds or fails.  

If the connection fails repeatedly, the `step` value keeps increasing (`2, 3, 4 … 104, 108…`) until it reaches an invalid state.  
Once this happens, the “Activate PayPal Payments” button stops working, onboarding never restarts, and there is no fallback or way to reset it in the UI.  

The only way to recover is to manually edit the database (`wp_options`) and reset the `step` value back to `1`.

---

### To Reproduce

1. Go to **WooCommerce → Settings → Payments → PayPal Payments**.  
2. Click **“Activate PayPal Payments”** and it will do nothing, making the user unable to complete onboarding.
3. Observe in the dev Console of the browser that the serialized option `woocommerce-ppcp-data-onboarding` updates with every click and the `step` increases by +1.  
4. Repeat the activation attempt several times.  
5. The value of `step` reaches a high number (e.g. `108`), onboarding breaks completely and the activation button no longer works.  

---

### Screenshots

**Broken state example** (from `/wp-json/wc/v3/wc_paypal/onboarding` response):  

```json
{
    "success": true,
    "data": {
        "completed": false,
        "step": 108,
        "isCasualSeller": true,
        "accept_card_payments": true,
        "products": [
            "virtual",
            "physical"
        ],
        "setup_done": false,
        "gateways_synced": false,
        "gateways_refreshed": false
    },
    "flags": {
        "canUseCasualSelling": true,
        "canUseVaulting": false,
        "canUseCardPayments": false,
        "canUseSubscriptions": false,
        "shouldSkipPaymentMethods": false,
        "canUseFastlane": false,
        "canUsePayLater": false
    }
}
```

**Working state example** (staging site, fresh onboarding):  

```json
{
    "success": true,
    "data": {
        "completed": false,
        "step": 1,
        "isCasualSeller": true,
        "products": ["virtual"],
        "gateways_synced": false,
        "gateways_refreshed": false
    },
    "flags": {
        "canUseCasualSelling": true,
        "canUseVaulting": false,
        "canUseCardPayments": false,
        "canUseSubscriptions": false,
        "shouldSkipPaymentMethods": false,
        "canUseFastlane": false,
        "canUsePayLater": false
    }
}
```

---

### Expected Behavior

- The `step` should represent the **current onboarding workflow step**, not a counter of attempts.  
- On failure, the onboarding should either:  
  - Retry the current step, OR  
  - Reset onboarding gracefully to `step: 1`, with a clear error message.  
- Merchants should always be able to retry onboarding from the UI, without needing to edit the database.  

---

### Actual Behavior

- Each failed attempt increments `step` indefinitely.  
- Once `step` exceeds the expected range, onboarding breaks permanently.  
- No error message is shown in the admin.  
- No “Reset” button is available.  
- Merchants must manually reset the option in `wp_options`.`woocommerce-ppcp-data-onboarding`  

---

### Environment

 - WordPress Version: 6.8.2  
 - WooCommerce Version: 10.2.1
 - Plugin Version: 3.1.0
 - PHP Version: 8.2.29
 - Browser: Chrome 130
 - Other active plugins: Divi CF7 Styler (Free) (2.3.3), Contact Form 7 (6.1.1), Polylang (3.7.3), Spotlight - Social Media Feeds (1.7.3), UpdraftPlus - Backup/Restore (1.25.7), Mercado Pago (8.5.2), WP-Optimize - Clean, Compress, Cache (4.3.0)

---

### Additional Details

**Option name affected:** `woocommerce-ppcp-data-onboarding`  
Stored in `wp_options`.  

**Workaround:**  
Reset the serialized value manually in the database. Example:  

```php
a:8:{
    s:9:"completed";b:0;
    s:4:"step";i:1;
    s:16:"is_casual_seller";b:1;
    s:20:"accept_card_payments";N;
    s:8:"products";a:1:{i:0;s:7:"virtual";}
    s:10:"setup_done";b:0;
    s:15:"gateways_synced";b:0;
    s:18:"gateways_refreshed";b:0;
}
```

After resetting the value of `step` to `1`, onboarding will work well again.

---

### Proposed Fix

1. Treat `step` as a **workflow state**, not an attempt counter.  
2. Add validation for maximum `step` values. If exceeded, reset to a safe default (e.g. `1`).  
3. Provide a **“Reset Onboarding” button in the admin UI** to allow merchants to retry onboarding without touching the database.  
4. Log and display clear error messages when onboarding fails, instead of silently breaking.  

---

<details><summary>System status</summary>

```
WordPress environment

WooCommerce version: 10.2.1
WooCommerce Legacy REST API package: not installed
Action Scheduler package: 3.9.3
WordPress version: 6.8.2
WordPress multisite: no
WordPress memory limit: 256 MB
WordPress debug mode: no
WordPress cron: yes
Language: en_US
External object cache: no

Server environment

Server info: Apache
Server architecture: Linux 4.18.0-553.7.1.el8_10.x86_64 x86_64
PHP version: 8.2.29
PHP post max size: 64 MB
PHP time limit: 180
PHP max input vars: 11000
cURL version: 7.61.1, OpenSSL/1.1.1k
SUHOSIN installed: no
MySQL version: 10.11.14-MariaDB-log
Max upload size: 64 MB
Default timezone: UTC
fsockopen/cURL: yes
SoapClient: yes
DOMDocument: yes
GZip: yes
Multibyte string: yes
Remote post: yes
Remote get: yes
```

</details>

### PR DESCRIPTION
**Pull request by AlexP11223**
Replaced the direct step increment via `setStep(currentStep + 1)` on the activation button click with `handleNext` from `OnboardingScreen` (which at least clamps the value), similar to the navigation component.

Hopefully this should fix #3707

### CODE REVIEW

File: modules/ppcp-settings/resources/js/Components/Screens/Onboarding/Steps/StepWelcome.js [hunk 1]
```diff
@@ -35,8 +35,7 @@ const StepWelcome = ( { setStep, currentStep } ) => {
 			  );
 
 	const handleActivatePayPal = () => {
-		const nextStep = currentStep + 1;
-		setStep( nextStep, 'user' );
+		onNext();
```
Comment (Dinamiko) [inline modules/ppcp-settings/resources/js/Components/Screens/Onboarding/Steps/StepWelcome.js]: `handleActivatePayPal` is now just a wrapper around onNext(). You could probably simplify the button to `onClick={ onNext }` directly and remove the function.

**Review by Dinamiko — APPROVED** [review]
PR looks good, just a minor suggestion.
