### PR TITLE
Remove plugin data options.

### LINKED ISSUE #1075: Remove plugin data after uninstalling. (121)
### Describe the Bug

After the plugin uninstalling, all plugin options and other data are not removed. So after deleting and reinstalling the plugin, the onboarded state along with settings persist. Users should have a way to reset the plugin configuration back to the default state and also remove the data when uninstalling the plugin.

### To Reproduce

1. Uninstall the plugin.
2. The data is not removed.

### Screenshots

Screen Shot 2022-12-12 at 15 28 41

### Expected Behavior

There should be an options to remove plugin data and scheduled actions after uninstalling the plugin or even without it.

### Actual Behavior

No options to reset plugin data.

### PR DESCRIPTION
**Pull request by Narek13**
**Issue**: #1075 

---

### Description

After the plugin uninstalling, all plugin options and other data are not removed. So after deleting and reinstalling the plugin, the onboarded state along with settings persist. Users should have a way to reset the plugin configuration back to the default state and also remove the data.

The PR will add 2 options in "Connection Tab" settings to clear the plugin data and scheduled actions when using the plugin or after uninstalling it.

### Steps to Test

1. The "**Remove PayPal Payments data from Database on uninstall**" and the "**Remove PayPal Payments data from Database(clear now button).**" exists in "Connection tab" settings.
2. When clicking on "Clear Now" button, you should first see the confirmation modal, then if clicked "ok" the data is removed, the "success" message is shown and you are redirected to "plugin connection" screen.
3. The "**Remove PayPal Payments data from Database on uninstall**" option is unchecked by default.
4. If the "**Remove PayPal Payments data from Database on uninstall**" option is checked when uninstalling the plugin then the plugin options and scheduled actions are removed

---

Closes #1075 .

### CODE REVIEW

File: modules/ppcp-uninstall/resources/js/ppcp-clear-db.js [hunk 1]
```diff
@@ -0,0 +1,43 @@
...
+    'DOMContentLoaded',
+    () => {
+        const config = PayPalCommerceGatewayClearDb;
+        if (!typeof (config)) {
+            return;
+        }
+
+        const clearDbConfig = config.clearDb;
+
+        jQuery(document).on('click', clearDbConfig.button, function () {
```
Comment (AlexP11223) [inline modules/ppcp-uninstall/resources/js/ppcp-clear-db.js]: :thinking: 

You can do just `button.click...` or `button.addEventListener...`. Or `jQuery(buttonSelector).click...` / `document.querySelector...`

If it can be `null`, then either `if` + `return` or `button?.addEventListener...` (for jQuery `null` does not matter).

File: modules/ppcp-uninstall/services.php [hunk 2]
```diff
@@ -0,0 +1,96 @@
...
+	},
+
+	'uninstall.clear-database-script-data'      => function( ContainerInterface $container ) : array {
+		return array(
+			'clearDb' => array(
+				'endpoint'            => \WC_AJAX::get_endpoint( $container->get( 'uninstall.clear-db-endpoint' ) ),
+				'nonce'               => wp_create_nonce( $container->get( 'uninstall.clear-db-endpoint' ) ),
+				'button'              => '.ppcp-clear_db_now',
+				'messageSelector'     => '.clear-db-info-message',
+				'ConfirmationMessage' => __( 'Are you sure? the operation will remove all plugin data.', 'woocommerce-paypal-payments' ),
```
Comment (AlexP11223) [inline modules/ppcp-uninstall/services.php]: not lower case like other fields?

**Review by Dinamiko — APPROVED** [review]

File: modules/ppcp-uninstall/services.php (hunk 2 above)
Comment (Narek13) [reply modules/ppcp-uninstall/services.php]: Thanks, was a mistake which I fixed here 554ae57cb1942e5ccc8dc22968e5ac76da225177

File: modules/ppcp-uninstall/resources/js/ppcp-clear-db.js (hunk 1 above)
Comment (Narek13) [reply modules/ppcp-uninstall/resources/js/ppcp-clear-db.js]: done. 2bb8ea9246ea3cb0bf365fa10ae72e1b66bd5947
